name: Deploy Manager
run-name: Deploy server manager to S3
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - manageServer/**
jobs:
  deploy-manager:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: manageServer
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::251780365797:role/GitHubOIDC
          role-session-name: ActionsDeploySession
          aws-region: ap-southeast-2

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: manageServer/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Pack sources
        run: npm run pack

      - name: Sync to S3
        run: aws s3 sync --delete dist s3://mcserver-management

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E2FYR9H7VEZOP9 --paths '/*'
